#
#  Copyright 2015 VMware, Inc.  All rights reserved.
#
#  SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
#  This code is Dual Licensed Apache License 2.0 or GPLv3
#
#  You may obtain a copy of the License(s) at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#      or
#
#      https://www.gnu.org/licenses/gpl-3.0.en.html
#
---
- name: enable autodeploy service
  service: name=vmware-rbd-watchdog enabled=yes state=restarted

- name: generating zip
  wait_for: timeout=3

- name: zip deploy-tftp files
  shell: 'cd /usr/share/ipxe && tar -cjf /tmp/deploy-tftpd.tbz2 *efi* undion*'

# todo investigate checksum issue
- name: Fetch deploy
  fetch: src=/tmp/deploy-tftpd.tbz2 dest=tmp/deploy-tftpd.tbz2 flat=yes validate_checksum=no
